---
title: "Traffic Fatalities"
author: "Lamar Hunt III"
date: "September 9, 2016"
output: html_document
---

# Introduction
In 2014, in response to concerns about having some of the highest rates of drunk driving fatalities in the United states, the South Carolina General Assembly enacted Emma's law, which requires first-time DUI offenders with a blood-alcohol content (BAC) greater than 0.15 to install an ignition interlock device on their vehicles for 6 months. The device requires drivers to blow into a breathalyzer before starting their car, as well as periodically throughout their drive. If the driver's BAC surpasses the legal limit, the car cannot be started. 

In this report, we examine whether there was a change in the proportion of drivers involved in a traffic fatality who were driving under the influence following the enactment of Emma's law. We use Fatality Analysis Reporting System (FARS) data provided by the National Highway Traffic Safety Administration (NHTSA). We perform an interrupted time series analysis on monthly data for years 2008 to 2015, with an interruption specified on October 1st, 2014, when the law came into effect. 

The findings will be informative for future legislators seeking to reduce the public health burden of drinking and driving. 


# Methods
## Data Acquisition
We used FARS data provided by the NHTSA, which we downloaded from ftp://ftp.nhtsa.dot.gov/fars. They provide data on every car fatality in the US from 1975 to 2015. The data we needed for the analysis can be found in the "person" file associated with each year. This file contains information regarding each person (drivers, passengers, pedestrians, bikers) involved in each fatality incident, such as their age, sex, BAC, and whether a police officer categorized them as drunk.

## Key Variable Definitions
The outcome is proportion of drivers involved in a traffic fatality who were reported to have been drunk by police, or who had BAC measured above 0.08. We chose 0.08 as the threshold because this is the legal limit in the state of South Carolina [citation]. We computed this proportion for each month from January of 2008 through Decemeber of 2015, and performed a log transformation.

FARS data records the date (down to the day) of each traffic fatality, but we chose to take proprtions on a monthly basis. Therefore, we defined the date (down to the day) of each proportion for each month using an average of the days within that month on which a drunk driving fatality occured, in order to capture the most representative date of the accidents for that month. This is in contrast to arbitrarily setting the date to be the first of the month. Thus, if by chance most drunk driving accidents occured very early or late in the month this would be captured by our choice of day for that monthly proportion on the time series. 

Finally, we defined a categorical variable indicating whether the date was prior to or after the onset of Emma's law (October 1st, 2014).

## Statistical Analysis
Let $Y_m$ be the log proportion of for month $m$, $D$ be the date, $c$ be October 1st, 2014, and $I(D > c)$ be an indicator variable. We performed an interrupted time series analysis with an interruption at October 1st, 2014, using the following linear model:
$$
Y_m = \beta_0 + \beta_1 D + \beta_2 X + \beta_3 (X I(D > c))
$$


# Results

# Discussion
## Limitations
We only had data on one year since the law was enacted, thereby limiting our results. Moreover, it is difficult to make any causal claims given the observational nature of the data. However, this is necessarily  

## Conclusion

## Further study

## References
http://scstatehouse.gov/sess120_2013-2014/bills/137.htm
```{r}

```


